name: Upload Dashboard Miranda

on:
  push:
    branches:
    - actions
jobs:
  create-envfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clean and Install Dependencies
        run: npm ci

      - name: Run Build
        run: npm run build
        env:
          VITE_URL_API: ${{secrets.VITE_URL_API}}

      - name: Make envfile
        run: echo "VITE_URL_API=${{secrets.VITE_URL_API}}" > env.local

      - name: Upload to AWS
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-west-3'
          SOURCE_DIR: 'build'